apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: proti-4x
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: igraj-4xproti
    newName: rg.fr-par.scw.cloud/djnd/igraj-4xproti
    newTag: '52bcddaf3ca263849836c97f9e690c6f10cfb981-dirty-20261008101201'
