apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: igraj-4xproti-data
spec:
  storageClassName: scw-bssd-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
